name = 'NavSide'
license = 'Apache 2.0'
licenselink = 'https://github.com/idevsig/navside/blob/main/LICENSE'
description = 'NavSide theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/idevsig/navside'

# If you have a running demo of the theme
demosite = 'https://navside.skiy.net'

# Taxonomy terms
tags = ['navigation', 'light', 'dark' ]
features = ['some', 'awesome', 'features']

[author]
  name = 'Jetsung Chan'
  homepage = 'https://github.com/jetsung'
