baseURL               = "https://example.com"
languageCode          = "zh-CN"
title                 = "爱开发导航"
theme                 = "navside"
themesDir             = "../.."
publishDir            = "public"

disableKinds = ["taxonomy", "term"] # 忽略告警和不生成 category 和 tag 的页面
disablePathToLower    = true
hasCJKLanguage        = true
enableGitInfo         = true

[params]
    author        = "Jetsung Chan"
    submit        = ""                                   # 左侧导航栏的"网站提交"
    about         = "https://forum.idev.top/p/about"     # 左侧导航栏的"关于导航"页面(./about)    
    enablePreLoad = true		    		             # 网站完全打开前预加载动画
    textPreLoad   = "爱开发网址导航" 		                # 预加载的动画文字, 只有当enablePreLoad=true时生效    
    expandSidebar = true                                 # 默认展开左侧边导航栏
    displayMode   = 2                                    # 显示模式，0.日间模式，1.深色(夜间)模式。2.实时模式，３.日间模式，４.夜间模式
    cardMode      = true                                 # 卡片模式

[params.seo]
    keywords      = "开发导航,程序员导航,技术资源导航,AI工具导航"
    description   = "爱开发精选导航 - 收录优质开发者工具、技术社区、云服务、AI平台等资源"

[params.images]
    favicon           = "favicon.ico"
    logosPath         = "assets/images/logos"			     # 网站每个导航地址logo存放地址
    defaultLogo       = "assets/images/default.webp"     
    logoExpandLight   = "assets/images/ns-expand-light.png"
    logoExpandDark    = "assets/images/ns-expand-dark.png"
    logoCollapseLight = "assets/images/ns.png"
    logoCollapseDark  = "assets/images/ns.png"    

[params.analytics]
    a51laid = "" # 51.LA 网站统计
    a51lack = "" #

[params.footer]
    copyright = ""

[markup.goldmark.renderer]
    unsafe = true # 忽略告警